<?php

namespace Database\Seeders;

use App\Models\Agent;
use Illuminate\Database\Seeder;

class AgentSeeder extends Seeder
{
    public function run(): void
    {
        $agents = [
            [
                'name' => 'Astra',
                'role' => 'Controller',
                'image_url' => 'images/agents/astra.png',
                'bg_url' => 'images/agents/astra/bg.jpg',
                'biography' => 'Recruited by the VALORANT Protocol as its sixteenth agent, "Astra", she continues to serve as an astral guardian in between her missions for the VP, though at times her two roles have come together. When the Protocol was keeping track of the fugitive Varun Batra whilst he was on the run from his former employer in Southern Asia, Astra discovered Batra was also in possession of a Guardian artifact, a set of five rings and a bracelet. Further compelled to bring him in, the VP was able to rescue and subsequently recruit Batra as agent "Harbor". With access to the bracelet, Astra was able to deduce from engravings left on it that it could function as a key to a lost Guardian city that she had never been able to find in her time as a Guardian. To her surprise however, Harbor revealed he had found it before; the "City of Flowers" was located in the Western Ghats of India, but Harbor had arrived there only to find it decimated and sabotaged.',
                'ability1' => 'Gravity Well',
                'ability2' => 'Nova Pulse',
                'ability3' => 'Nebula',
                'ultimate' => 'Astral Form',
                'ability1_desc' => 'Pulls players toward the center before exploding.',
                'ability2_desc' => 'Concusses players in its area of effect.',
                'ability3_desc' => 'Deploys smoke clouds that block vision.',
                'ultimate_desc' => 'Enter Astral Form to place stars and activate abilities.',
                'ability1_url' => 'images/agents/astra/ability1.webp',
                'ability2_url' => 'images/agents/astra/ability2.webp',
                'ability3_url' => 'images/agents/astra/ability3.webp',
                'ultimate_url' => 'images/agents/astra/ultimate.webp',
            ],
            [
                'name' => 'Breach',
                'role' => 'Initiator',
                'image_url' => 'images/agents/breach.png',
                'bg_url' => 'images/agents/breach/bg.jpg',
                'biography' => 'A criminal from Sweden, Erik Torsten was set to be convicted along with the rest of his family for their crimes. As he was a double congenital amputee however, the judge was pitiful and lenient towards him, giving him a smaller sentence that soon allowed Erik to return to his old ways. Building himself his own mechanical arms to use, Erik would hit back with his own criminal assignments, becoming so notorious for the terrible things he had done that he eventually had to go into hiding and effectively exile himself from his home. During these times, he also encountered the young Brazilian Tayane Alves, who worked alongside him for a while and provided some major upgrades to his arms, resulting in the carbon-steel titanium-plating version that he uses to this day.',
                'ability1' => 'Aftershock',
                'ability2' => 'Flashpoint',
                'ability3' => 'Fault Line',
                'ultimate' => 'Rolling Thunder',
                'ability1_desc' => 'Fires a slow-activating burst through a wall.',
                'ability2_desc' => 'Flash through walls to blind opponents.',
                'ability3_desc' => 'Seismic quake that disorients players in its path.',
                'ultimate_desc' => 'Powerful quake in a large cone, stunning all caught.',
                'ability1_url' => 'images/agents/breach/ability1.webp',
                'ability2_url' => 'images/agents/breach/ability2.webp',
                'ability3_url' => 'images/agents/breach/ability3.webp',
                'ultimate_url' => 'images/agents/breach/ultimate.webp',
            ],
            [
                'name' => 'Brimstone',
                'role' => 'Controller',
                'image_url' => 'images/agents/brimstone.png',
                'bg_url' => 'images/agents/brimstone/bg.jpg',
                'biography' => "Liam \"Brimstone\" Byrne is the commander of the VALORANT Protocol, a secretive organization tasked with protecting Earth from cataclysmic disasters and dangerous situations involving radianite. A former firefighter and soldier from Baltimore, Byrne is fiercely loyal to all his allies and organizations, always keeps his squadmates close. But although he would do anything for them, Byrne hasn't always been able to save everyone. After the death of a close friend, Tariq Porter, his loss greatly affected Byrne, haunted by what had happened despite all his own best efforts to save him. It was around this time that he would then join Kingdom Corporation, giving him something at a time when he needed it most. Byrne would go on to become a veteran of Kingdom's K-SEC branch, once again developing a strong loyalty to his employer.",
                'ability1' => 'Incendiary',
                'ability2' => 'Stim Beacon',
                'ability3' => 'Sky Smoke',
                'ultimate' => 'Orbital Strike',
                'ability1_desc' => 'Launches an incendiary grenade to zone enemies.',
                'ability2_desc' => 'Places a stim beacon that grants rapid fire.',
                'ability3_desc' => 'Deploys smokes from the sky for area denial.',
                'ultimate_desc' => 'Orbital laser strikes the targeted area.',
                'ability1_url' => 'images/agents/brimstone/ability1.webp',
                'ability2_url' => 'images/agents/brimstone/ability2.webp',
                'ability3_url' => 'images/agents/brimstone/ability3.webp',
                'ultimate_url' => 'images/agents/brimstone/ultimate.webp',
            ],
            [
                'name' => 'Chamber',
                'role' => 'Sentinel',
                'image_url' => 'images/agents/chamber.png',
                'bg_url' => 'images/agents/chamber/bg.jpg',
                "biography" => "The Frenchman Vincent Fabron lives his life in search of one necessary goal, willing to sacrifice anything that gets in his way of achieving it. He has spent much of his time involved with combat and weapons, having worked for the French military before becoming a PMC marksman and then a weapons designer for Kingdom Defense. His employment at Kingdom was only a stepping stone for him though, as by this point he was already set on his path in pursuit of his sacred truth.",
                'ability1' => 'Trademark',
                'ability2' => 'Headhunter',
                'ability3' => 'Rendezvous',
                'ultimate' => 'Tour De Force',
                'ability1_desc' => 'Trap that scans for enemies and destabilizes terrain.',
                'ability2_desc' => 'Powerful handgun with high accuracy and damage.',
                'ability3_desc' => 'Teleport anchors for fast repositioning.',
                'ultimate_desc' => 'High-powered sniper rifle that kills on hit.',
                'ability1_url' => 'images/agents/chamber/ability1.webp',
                'ability2_url' => 'images/agents/chamber/ability2.webp',
                'ability3_url' => 'images/agents/chamber/ability3.webp',
                'ultimate_url' => 'images/agents/chamber/ultimate.webp',
            ],
            [
                'name' => 'Clove',
                'role' => 'Controller',
                'image_url' => 'images/agents/clove.png',
                'bg_url' => 'images/agents/clove/bg.jpg',
                "biography" => "The young Scottish VALORANT agent Clove possesses powers unprecedented among even their fellow radiants - the power over the essences of life and immortality. Each death instead brings them to a whole new world, a junction between the realms of the living and the dead, one that Clove will journey through on their way to return to life and resurrect themselves. But such abilities are unlikely to be a blessing forever, and Clove themselves finds they can never spend too long in the junction beyond life as the longer they spend there, the harder it is to return.",
                'ability1' => 'Pick-Me-Up',
                'ability2' => 'Meddle',
                'ability3' => 'Ruse',
                'ultimate' => 'Not Dead Yet',
                'ability1_desc' => 'Temporarily boosts movement speed and health.',
                'ability2_desc' => 'Throws a projectile that weakens enemies.',
                'ability3_desc' => 'Creates deceptive smokes to obscure vision.',
                'ultimate_desc' => 'Revive yourself shortly after dying.',
                'ability1_url' => 'images/agents/clove/ability1.webp',
                'ability2_url' => 'images/agents/clove/ability2.webp',
                'ability3_url' => 'images/agents/clove/ability3.webp',
                'ultimate_url' => 'images/agents/clove/ultimate.webp',
            ],

            [
                'name' => 'Cypher',
                'role' => 'Sentinel',
                'image_url' => 'images/agents/cypher.png',
                'bg_url' => 'images/agents/cypher/bg.jpg',
                "biography" => "Cypher is constantly gathering secrets, information, and intel, to the point of managing to retrieve the passwords of everyone in the VALORANT Protocol. His continued passion to gather whatever information he can find is not always shared by his teammates, as Jett found out the hard way during an undercover mission in Los Angeles. He keeps most of this information to himself, making sure that no one ever discovers them and only revealing anything he knows for a price. In contrast of how he knows a lot about his allies, they do not know much about him, and he prefers to keep it that way.",
                'ability1' => 'Trapwire',
                'ability2' => 'Cyber Cage',
                'ability3' => 'Spycam',
                'ultimate' => 'Neural Theft',
                'ability1_desc' => 'Deploys a tripwire between two walls.',
                'ability2_desc' => 'Creates a temporary vision-blocking cage.',
                'ability3_desc' => 'Remote-controlled camera with dart tag.',
                'ultimate_desc' => 'Reveal locations of all enemies using a corpse.',
                'ability1_url' => 'images/agents/cypher/ability1.webp',
                'ability2_url' => 'images/agents/cypher/ability2.webp',
                'ability3_url' => 'images/agents/cypher/ability3.webp',
                'ultimate_url' => 'images/agents/cypher/ultimate.webp',
            ],
            [
                'name' => 'Deadlock',
                'role' => 'Sentinel',
                'image_url' => 'images/agents/deadlock.png',
                'bg_url' => 'images/agents/deadlock/bg.jpg',
                "biography" => "At one point during the VALORANT Protocol's investigations into a Los Angeles-based Kingdom Corporation project called \"Landfall\", the organization was able to pick up on chatter about a cargo pickup happening in Norway. Viewing this to be something of interest, the Protocol sent Sova to follow the team and track down its destination. Leading him to a specialized facility known as The Vault in the far northern archipelago of Svalbard, Sova arrived to find no activity there, no signs of life, except for a faint beacon activated from within. Entering The Vault, the Russian eventually made his way to a containment room to discover the aftermath of an attack, with all the pickup team dead except for one remaining survivor - a blonde-haired woman with one of her arms completely obliterated.",
                'ability1' => 'Sonic Sensor',
                'ability2' => 'Barrier Mesh',
                'ability3' => 'GravNet',
                'ultimate' => 'Annihilation',
                'ability1_desc' => 'Deploys a sensor that concusses enemies.',
                'ability2_desc' => 'Barrier that blocks movement and projectiles.',
                'ability3_desc' => 'Tether net slows and pulls enemies inward.',
                'ultimate_desc' => 'Captures a single enemy and pulls them to death.',
                'ability1_url' => 'images/agents/deadlock/ability1.webp',
                'ability2_url' => 'images/agents/deadlock/ability2.webp',
                'ability3_url' => 'images/agents/deadlock/ability3.webp',
                'ultimate_url' => 'images/agents/deadlock/ultimate.webp',
            ],
            [
                'name' => 'Fade',
                'role' => 'Initiator',
                'image_url' => 'images/agents/fade.png',
                'bg_url' => 'images/agents/fade/bg.jpg',
                'biography' => 'A Radiant from Türkiye, Hazal Eyletmez searches for a person of importance to her after he was taken from her. Using her ability to see nightmare-visions, her interpretations initially led her to suspect that he had been kidnapped by a secret organization she found to be the VALORANT Protocol. Eyletmez decided to contact the Protocol under an anonymous mark, threatening to expose the organization if she found out they were responsible for the kidnapping. When they appeared to only have interest in tracking her down rather than take her seriously, she then contacted each agent personally with a dossier about them to show how much she knew about VALORANTs people and what she could expose to the public if they had no interest in proving their innocence.',
                'ability1' => 'Prowler',
                'ability2' => 'Seize',
                'ability3' => 'Haunt',
                'ultimate' => 'Nightfall',
                'ability1_desc' => 'Summons a creature that nearsights enemies.',
                'ability2_desc' => 'Tether orb that decays and holds enemies in place.',
                'ability3_desc' => 'Reveals enemy positions via haunting entity.',
                'ultimate_desc' => 'Nightmare energy trails and deafens all enemies.',
                'ability1_url' => 'images/agents/fade/ability1.webp',
                'ability2_url' => 'images/agents/fade/ability2.webp',
                'ability3_url' => 'images/agents/fade/ability3.webp',
                'ultimate_url' => 'images/agents/fade/ultimate.webp',
            ],
            [
                'name' => 'Gekko',
                'role' => 'Initiator',
                'image_url' => 'images/agents/gekko.png',
                'bg_url' => 'images/agents/gekko/bg.jpg',
                'biography' => "Born and raised in Los Angeles, California, Mateo Armendáriz De la Fuente, call-sign 'Gekko', is VALORANT's twenty-second recruit and the owner of Dizzy, Mosh, Thrash, and Wingman, a crew of four creatures known as radivores with the ability to transform from their primary globule state into mimicked animalistic forms. Previously property of K-SEC, these radivores now live with Gekko, often traveling with him wherever he goes within their small carrier that Gekko wears as a sash, from which they'll emerge and take form at a moment's notice to assist him.",
                'ability1' => 'Dizzy',
                'ability2' => 'Mosh Pit',
                'ability3' => 'Wingman',
                'ultimate' => 'Thrash',
                'ability1_desc' => 'Releases a blinding plasma from Dizzy.',
                'ability2_desc' => 'Throws a sticky explosive blob.',
                'ability3_desc' => 'Sends Wingman to plant or defuse the Spike.',
                'ultimate_desc' => 'Unleashes Thrash to detain enemies in a small radius.',
                'ability1_url' => 'images/agents/gekko/ability1.webp',
                'ability2_url' => 'images/agents/gekko/ability2.webp',
                'ability3_url' => 'images/agents/gekko/ability3.webp',
                'ultimate_url' => 'images/agents/gekko/ultimate.webp',
            ],
            [
                'name' => 'Harbor',
                'role' => 'Controller',
                'image_url' => 'images/agents/harbor.png',
                'bg_url' => 'images/agents/harbor/bg.jpg',
                'biography' => "A former task force agent, Varun Batra is the unexpected owner of an ancient and powerful artifact with the power to control and summon masses of water out of nothing. Previously working for REALM to recover such sorts of items from the black market and return them to their rightful owners, Batra was regarded as a kind-hearted man but also a deadly force to deal with in combat. His dedication to the cause through years of service fighting criminals earned him a reputation as a hero and a legend.",
                'ability1' => 'Cascade',
                'ability2' => 'Cove',
                'ability3' => 'High Tide',
                'ultimate' => 'Reckoning',
                'ability1_desc' => 'Pushes forward a moving wall of water.',
                'ability2_desc' => 'Casts a sphere of water that blocks bullets.',
                'ability3_desc' => 'Deploys a controllable water wall.',
                'ultimate_desc' => 'Releases geysers that concuss enemies in waves.',
                'ability1_url' => 'images/agents/harbor/ability1.webp',
                'ability2_url' => 'images/agents/harbor/ability2.webp',
                'ability3_url' => 'images/agents/harbor/ability3.webp',
                'ultimate_url' => 'images/agents/harbor/ultimate.webp',
            ],
            [
                'name' => 'Iso',
                'role' => 'Duelist',
                'image_url' => 'images/agents/iso.png',
                'bg_url' => 'images/agents/iso/bg.jpg',
                'biography' => "Chinese hitman Li Zhao Yu is a radiant with the ability to transmute ambient, intangible radianite energy into solid, durable constructs. A former assassin for the Scions of Hourglass, Li gained a fearsome reputation for his high effectiveness. Though it was said that anyone who would go up against him would disappear for good, rumors still spread beyond about the 'Dead Lilac', a bulletproof wizard who could take out entire squads with one round and condemn targets to their fate in a flash of purple.",
                'ability1' => 'Double Tap',
                'ability2' => 'Undercut',
                'ability3' => 'Contingency',
                'ultimate' => 'Kill Contract',
                'ability1_desc' => 'Defeating enemies creates a shield orb.',
                'ability2_desc' => 'Shoots a molecular disruptor to debuff enemies.',
                'ability3_desc' => 'Creates a kinetic shield wall while moving forward.',
                'ultimate_desc' => 'Pulls an enemy into a 1v1 battlefield.',
                'ability1_url' => 'images/agents/iso/ability1.webp',
                'ability2_url' => 'images/agents/iso/ability2.webp',
                'ability3_url' => 'images/agents/iso/ability3.webp',
                'ultimate_url' => 'images/agents/iso/ultimate.webp',
            ],
            [
                'name' => 'Jett',
                'role' => 'Duelist',
                'image_url' => 'images/agents/jett.png',
                'bg_url' => 'images/agents/jett/bg.jpg',
                'biography' => "A radiant from Seoul, South Korea, Han Sunwoo (Korean: 한선우) had her life forever changed by one person - her counterpart from Omega Earth. As a chef in her early life, Han was shot and hunted down by Ω-Jett outside the restaurant she worked at. In the ensuing fight, a 'freak storm' was caused as a result of the wind-powered abilities of the two Hans that all but destroyed the restaurant. α-Han was forced to flee the scene soon after she made it out of the encounter.",
                'ability1' => 'Cloudburst',
                'ability2' => 'Updraft',
                'ability3' => 'Tailwind',
                'ultimate' => 'Blade Storm',
                'ability1_desc' => 'Throws a cloud of vision-blocking smoke.',
                'ability2_desc' => 'Dashes high into the air.',
                'ability3_desc' => 'Quick horizontal dash in the movement direction.',
                'ultimate_desc' => 'Equip deadly throwing knives with reset on kill.',
                'ability1_url' => 'images/agents/jett/ability1.webp',
                'ability2_url' => 'images/agents/jett/ability2.webp',
                'ability3_url' => 'images/agents/jett/ability3.webp',
                'ultimate_url' => 'images/agents/jett/ultimate.webp',
            ],
            [
                'name' => 'KAYO',
                'role' => 'Initiator',
                'image_url' => 'images/agents/kayo.png',
                'bg_url' => 'images/agents/kayo/bg.jpg',
                'biography' => "A robot from an alternate future, KAY/O was created by the humans of that time to fight back against the radiants that they were at war with. Using the power of polarized radianite, KAY/O proved effective in shutting down radiants' abilities, making them easier to eliminate. The radiant Reyna was of particularly high importance to KAY/O for her actions against humanity, and KAY/O was able to eventually eliminate her. However, at this point humans had already suffered severe losses",
                'ability1' => 'FRAG/ment',
                'ability2' => 'FLASH/drive',
                'ability3' => 'ZERO/point',
                'ultimate' => 'NULL/cmd',
                'ability1_desc' => 'Throws a grenade that explodes in pulses.',
                'ability2_desc' => 'Flash grenade that explodes after a delay.',
                'ability3_desc' => 'Blade that suppresses enemy abilities in radius.',
                'ultimate_desc' => 'Overclock and suppress enemies with faster fire.',
                'ability1_url' => 'images/agents/kayo/ability1.webp',
                'ability2_url' => 'images/agents/kayo/ability2.webp',
                'ability3_url' => 'images/agents/kayo/ability3.webp',
                'ultimate_url' => 'images/agents/kayo/ultimate.webp',
            ],
            [
                'name' => 'Killjoy',
                'role' => 'Sentinel',
                'image_url' => 'images/agents/killjoy.png',
                'bg_url' => 'images/agents/killjoy/bg.jpg',
                'biography' => "Klara Böhringer is an inventor from Germany who was born to one parent with Germanic ancestry. A nominee for the Distinguished Inventor award, Böhringer became the lead for Kingdom's R&D department at the age of 18. Incredibly successful, she had many breakthroughs during her time at Kingdom with several of her creations and innovations.",
                'ability1' => 'Nanoswarm',
                'ability2' => 'Alarmbot',
                'ability3' => 'Turret',
                'ultimate' => 'Lockdown',
                'ability1_desc' => 'Deploys a grenade that explodes in a damaging swarm.',
                'ability2_desc' => 'Places a bot that debuffs and alerts on proximity.',
                'ability3_desc' => 'Deploys an auto-firing turret.',
                'ultimate_desc' => 'Locks down an area, detaining enemies caught.',
                'ability1_url' => 'images/agents/killjoy/ability1.webp',
                'ability2_url' => 'images/agents/killjoy/ability2.webp',
                'ability3_url' => 'images/agents/killjoy/ability3.webp',
                'ultimate_url' => 'images/agents/killjoy/ultimate.webp',
            ],
            [
                'name' => 'Neon',
                'role' => 'Duelist',
                'image_url' => 'images/agents/neon.png',
                'bg_url' => 'images/agents/neon/bg.jpg',
                'biography' => "Raised in Manila, Philippines, Tala Nicole Dimaapi Valdez is a Radiant empowered by her bioelectricity which has enlaced itself with Earth's radianite mesh. A young but former veteran at K-SEC, she was recruited by the VALORANT Protocol as part of their Omega Project, specifically to utilize her electric abilities as they attempted to power an Alpha-Omega teleporter. Accepting a position there as their nineteenth agent, 'Neon', Valdez left her home to join the Protocol and now seeks to help establish a stable connection that will finally allow the VP to cross over to Omega Earth.",
                'ability1' => 'Fast Lane',
                'ability2' => 'Relay Bolt',
                'ability3' => 'High Gear',
                'ultimate' => 'Overdrive',
                'ability1_desc' => 'Creates two walls of electricity as a lane.',
                'ability2_desc' => 'Shock bolts that concuss enemies.',
                'ability3_desc' => 'Accelerates movement with a slide.',
                'ultimate_desc' => 'Shoots a beam of lightning with extreme accuracy.',
                'ability1_url' => 'images/agents/neon/ability1.webp',
                'ability2_url' => 'images/agents/neon/ability2.webp',
                'ability3_url' => 'images/agents/neon/ability3.webp',
                'ultimate_url' => 'images/agents/neon/ultimate.webp',
            ],
            [
                'name' => 'Omen',
                'role' => 'Controller',
                'image_url' => 'images/agents/omen.png',
                'bg_url' => 'images/agents/omen/bg.jpg',
                'biography' => "For many years the phantom radiant Omen had no memory of his past and how he came to be in his current state. Firstly working alongside Dr. Sabine Callas (one of his only apparent links to who he used to be) at Kingdom Corporation, he would then go on join her in the founding of the VALORANT Protocol. During his time as a secret agent, Omen was driven by his search to discover who he previously was. Without answers he was unable to find peace, his predicament being only a nightmare for him to live in.",
                'ability1' => 'Shrouded Step',
                'ability2' => 'Paranoia',
                'ability3' => 'Dark Cover',
                'ultimate' => 'From the Shadows',
                'ability1_desc' => 'Teleports a short distance to a nearby location.',
                'ability2_desc' => 'Fires a shadow that nearsights enemies.',
                'ability3_desc' => 'Deploys smoke that phases through walls.',
                'ultimate_desc' => 'Teleport anywhere on the map.',
                'ability1_url' => 'images/agents/omen/ability1.webp',
                'ability2_url' => 'images/agents/omen/ability2.webp',
                'ability3_url' => 'images/agents/omen/ability3.webp',
                'ultimate_url' => 'images/agents/omen/ultimate.webp',
            ],
            [
                'name' => 'Phoenix',
                'role' => 'Duelist',
                'image_url' => 'images/agents/phoenix.png',
                'bg_url' => 'images/agents/phoenix/bg.jpg',
                'biography' => "Jamie Adeyemi is a radiant hailing from the Peckham district in London, England. Growing up, Adeyemi attended a Performing Arts school in the area but was later suspended. Recruited into the VALORANT Protocol as its ninth agent, 'Phoenix', Adeyemi was heavily involved with the Protocol's activities from 10 AFL onwards. With much information kept from him as need-to-know as a recent recruit, he was unable to prevent a spike detonation in Venice whilst on a solo mission. Phoenix was given another opportunity to stop one the next day when another attack occurred in Rabat, and it was here that he first came face-to-face with the sole perpetrator, his own Omega counterpart. Frustrated with how much was being kept in the dark, despite going on to prevent the detonation this time with the help of a team, Phoenix was finally filled in on the threat posed by Omega Earth.",
                'ability1' => 'Blaze',
                'ability2' => 'Curveball',
                'ability3' => 'Hot Hands',
                'ultimate' => 'Run it Back',
                'ability1_desc' => 'Creates a wall of fire that heals and blocks vision.',
                'ability2_desc' => 'Throws a curving flashbang.',
                'ability3_desc' => 'Throws a fireball that heals Phoenix and damages enemies.',
                'ultimate_desc' => 'Marks a location and respawns there after a duration.',
                'ability1_url' => 'images/agents/phoenix/ability1.webp',
                'ability2_url' => 'images/agents/phoenix/ability2.webp',
                'ability3_url' => 'images/agents/phoenix/ability3.webp',
                'ultimate_url' => 'images/agents/phoenix/ultimate.webp',
            ],
            [
                'name' => 'Raze',
                'role' => 'Duelist',
                'image_url' => 'images/agents/raze.png',
                'bg_url' => 'images/agents/raze/bg.jpg',
                'biography' => "Tayane Alves is an engineer coming from Salvador, Bahia, Brazil, with a strong enthusiasm for explosives and paint - usually combined. Holding strong objections towards Kingdom Corporation's operations in Bahia, Alves was involved in driving the company out of her home state and forcing them to abandon their sites there, the marks of her tools staining the plots as a testament to her victories. Hired since then to work for the VALORANT Protocol as its twelfth agent, 'Raze', Alves now sows her chaos against bigger threats to Alpha Earth. However, as the paint fades from Salvador's walls, Raze cannot afford to leave her home completely behind, lest Kingdom look to make its return there.",
                'ability1' => 'Boom Bot',
                'ability2' => 'Blast Pack',
                'ability3' => 'Paint Shells',
                'ultimate' => 'Showstopper',
                'ability1_desc' => 'Deploys a robot that chases enemies and explodes.',
                'ability2_desc' => 'Throws a sticky satchel that can be detonated.',
                'ability3_desc' => 'Throws a cluster grenade.',
                'ultimate_desc' => 'Fires a massive rocket launcher.',
                'ability1_url' => 'images/agents/raze/ability1.webp',
                'ability2_url' => 'images/agents/raze/ability2.webp',
                'ability3_url' => 'images/agents/raze/ability3.webp',
                'ultimate_url' => 'images/agents/raze/ultimate.webp',
            ],
            [
                'name' => 'Reyna',
                'role' => 'Duelist',
                'image_url' => 'images/agents/reyna.png',
                'bg_url' => 'images/agents/reyna/bg.jpg',
                'biography' => "Zyanya Mondragón is a Radiant from Mexico with the power to absorb life energy from the souls of people that she kills. After being affected by a disastrous event involving machines, Mondragón has a strong dislike for technology and humanity, believing herself and her fellow radiants to be the true future for Alpha Earth. Before her time as a VALORANT Protocol agent, she set up a sanctuary to help people escape from Kingdom and heal, establishing a community there and becoming their protector and avenger.",
                'ability1' => 'Leer',
                'ability2' => 'Devour',
                'ability3' => 'Dismiss',
                'ultimate' => 'Empress',
                'ability1_desc' => 'Throws an ethereal eye that nearsights enemies.',
                'ability2_desc' => 'Heals from slain enemies.',
                'ability3_desc' => 'Enters a ghostly form, becoming invulnerable.',
                'ultimate_desc' => 'Buffs combat stats and enables chained use of Devour/Dismiss.',
                'ability1_url' => 'images/agents/reyna/ability1.webp',
                'ability2_url' => 'images/agents/reyna/ability2.webp',
                'ability3_url' => 'images/agents/reyna/ability3.webp',
                'ultimate_url' => 'images/agents/reyna/ultimate.webp',
            ],
            [
                'name' => 'Sage',
                'role' => 'Sentinel',
                'image_url' => 'images/agents/sage.png',
                'bg_url' => 'images/agents/sage/bg.jpg',
                'biography' => "Wei Ling Ying (Chinese: 魏玲瑩) is a radiant monk coming from China. Going on to become an agent for the VALORANT Protocol as its seventh recruit, 'Sage', Wei was able to work her way quickly up the ranks, with the Protocol's superiors identifying natural leadership qualities in her. Sage is currently active in VALORANT's radiant agent recruitment and training, interacting with multiple new radiants upon recruitment and taking the lead on its radiant training program.",
                'ability1' => 'Barrier Orb',
                'ability2' => 'Slow Orb',
                'ability3' => 'Healing Orb',
                'ultimate' => 'Resurrection',
                'ability1_desc' => 'Creates a solid wall.',
                'ability2_desc' => 'Slows enemies in a field.',
                'ability3_desc' => 'Heals herself or an ally.',
                'ultimate_desc' => 'Revives a fallen teammate.',
                'ability1_url' => 'images/agents/sage/ability1.webp',
                'ability2_url' => 'images/agents/sage/ability2.webp',
                'ability3_url' => 'images/agents/sage/ability3.webp',
                'ultimate_url' => 'images/agents/sage/ultimate.webp',
            ],
            [
                'name' => 'Skye',
                'role' => 'Initiator',
                'image_url' => 'images/agents/skye.png',
                'bg_url' => 'images/agents/skye/bg.jpg',
                'biography' => "A Radiant from Nimbin, Australia, Kirra Foster spent years fighting against Kingdom Corporation's ventures in Eastern Australia. Resisting from Sawn Rocks to Kangaroo Valley, her efforts against Kingdom earned her the title of the 'Great Reclaimer'. Later approached by the VALORANT Protocol to become an agent, Foster was initially unsure of joining as she didn't want to give up her fight against Kingdom and leave her homeland unprotected. However, when Sage decided to contact and direct her to a massive rift in the sky near her home, telling her there were many more like that one across the world, Kirra realized that the fight was bigger than just her home territory. Finally answering the call, she now serves as the Protocol's fourteenth agent, 'Skye'.",
                'ability1' => 'Regrowth',
                'ability2' => 'Trailblazer',
                'ability3' => 'Guiding Light',
                'ultimate' => 'Seekers',
                'ability1_desc' => 'Heals allies in a radius.',
                'ability2_desc' => 'Sends out a tiger trinket to control and concuss enemies.',
                'ability3_desc' => 'Equips and sends out a hawk flash.',
                'ultimate_desc' => 'Sends seekers to track and nearsight enemies.',
                'ability1_url' => 'images/agents/skye/ability1.webp',
                'ability2_url' => 'images/agents/skye/ability2.webp',
                'ability3_url' => 'images/agents/skye/ability3.webp',
                'ultimate_url' => 'images/agents/skye/ultimate.webp',
            ],
            [
                'name' => 'Sova',
                'role' => 'Initiator',
                'image_url' => 'images/agents/sova.png',
                'bg_url' => 'images/agents/sova/bg.jpg',
                'biography' => "Hailing from the town of Severomorsk, in Murmansk Oblast, Russia, Sasha Novikov (Russian: Саша Новиков) is an archer who became an agent for the VALORANT Protocol as its sixth recruit, 'Sova'. With his right eye replaced with a mechanical one after he lost it, Sova primarily serves as the team's scout, gathering information and searching for targets using olden methods should technology come up short. Being highly capable and reliable both in the field and with his work, whilst also having experience with multiple radianite-related events (having traveled through a rift and having met his Omega counterpart), Sova has earned a reputation of being one of the Protocol's most trusted agents, especially to the organization's commander, Brimstone.",
                'ability1' => 'Shock Bolt',
                'ability2' => 'Owl Drone',
                'ability3' => 'Recon Bolt',
                'ultimate' => 'Hunter\'s Fury',
                'ability1_desc' => 'Fires an explosive bolt that emits shockwaves on impact.',
                'ability2_desc' => 'Deploys a drone that can scout and fire a marking dart.',
                'ability3_desc' => 'Launches a bolt that reveals enemies in its line of sight.',
                'ultimate_desc' => 'Fires up to three long-range energy blasts that pass through walls.',
                'ability1_url' => 'images/agents/sova/ability1.webp',
                'ability2_url' => 'images/agents/sova/ability2.webp',
                'ability3_url' => 'images/agents/sova/ability3.webp',
                'ultimate_url' => 'images/agents/sova/ultimate.webp',
            ],
            [
                'name' => 'Tejo',
                'role' => 'Initiator',
                'image_url' => 'images/agents/tejo.png',
                'bg_url' => 'images/agents/tejo/bg.jpg',
                'biography' => "Colombian Tejo is the VALORANT Protocol's twenty-seventh recruit. A formerly-retired intelligence consultant, his unexpected arrival at the Protocol comes as a surprise to the rest of its agents, returning from a period of now interrupted leave to find a stranger suddenly wandering around HQ.",
                'ability1' => 'Flux Charge',
                'ability2' => 'Ricochet',
                'ability3' => 'Null Zone',
                'ultimate' => 'Cascade Surge',
                'ability1_desc' => 'Throws a charge that sticks to surfaces and emits a concussive blast after a short delay.',
                'ability2_desc' => 'Fires an energy shot that bounces off walls and briefly disorients hit enemies.',
                'ability3_desc' => 'Deploys a field that suppresses enemy abilities and reveals them while active.',
                'ultimate_desc' => 'Unleashes a large wave of energy that passes through walls and nearsights all enemies in its path.',
                'ability1_url' => 'images/agents/tejo/ability1.webp',
                'ability2_url' => 'images/agents/tejo/ability2.webp',
                'ability3_url' => 'images/agents/tejo/ability3.webp',
                'ultimate_url' => 'images/agents/tejo/ultimate.webp',
            ],
            [
                'name' => 'Viper',
                'role' => 'Controller',
                'image_url' => 'images/agents/viper.png',
                'bg_url' => 'images/agents/viper/bg.jpg',
                'biography' => "American chemist Sabine Callas was a pivotal figure during the modern rediscovery of radianite. A distinguished scientist working at Kingdom Corporation, she had been one of the first to investigate the substance when the organization came across it. However, news of what Callas and Kingdom were about to uncover reached the Scions of Hourglass, an organization that already secretly knew about radianite and didn't want its existence to become public knowledge again to Alpha. Hourglass proceeded to send their most talented asset, the assassin 'Ghost', to kill Callas. On the day of the attempted assassination however while Callas was working in her lab, she was able to defend herself, with Ghost being hit in the face by a vial of chemicals she had been holding before he had then ended up being trapped in a test chamber that Callas proceeded to activate while he was still inside.",
                'ability1' => 'Snake Bite',
                'ability2' => 'Poison Cloud',
                'ability3' => 'Toxic Screen',
                'ultimate' => 'Viper\'s Pit',
                'ability1_desc' => 'Releases a pool of acid that damages enemies.',
                'ability2_desc' => 'Throws a gas emitter cloud.',
                'ability3_desc' => 'Creates a long wall of gas.',
                'ultimate_desc' => 'Creates a massive gas cloud that decays enemies.',
                'ability1_url' => 'images/agents/viper/ability1.webp',
                'ability2_url' => 'images/agents/viper/ability2.webp',
                'ability3_url' => 'images/agents/viper/ability3.webp',
                'ultimate_url' => 'images/agents/viper/ultimate.webp',
            ],
            [
                'name' => 'Vyse',
                'role' => 'Duelist',
                'image_url' => 'images/agents/vyse.png',
                'bg_url' => 'images/agents/vyse/bg.jpg',
                'biography' => "A former Kingdom researcher on the Interverse, Vyse is now a metallic radiant who has a radianite-infused alloy flowing through her. Captured by the Scions of Hourglass and held at their Elder Grotto facility under the remote island of Jan Mayen, Vyse was eventually able to break free after her containment unit was damaged by gunfire when the site was attacked and taken over by the VALORANT Protocol. Laying waste to other Hourglass hideouts in revenge, she was then confronted by a VALORANT strike team in Seoul, who eventually convinced Vyse to join them. Recruited as their twenty-sixth agent, Vyse now continues her work on researching the Interverse as the lead for the Protocol's own project.",
                'ability1' => 'Phantom Step',
                'ability2' => 'Shatter Ring',
                'ability3' => 'Drift Core',
                'ultimate' => 'Singularity Collapse',
                'ability1_desc' => 'Short-range teleport to a visible nearby location.',
                'ability2_desc' => 'Throws a ring that explodes, dealing damage and deafening enemies.',
                'ability3_desc' => 'Briefly hover mid-air, slowing fall speed and allowing repositioning.',
                'ultimate_desc' => 'Unleashes a massive singularity that pulls in enemies and detonates for high damage.',
                'ability1_url' => 'images/agents/vyse/ability1.webp',
                'ability2_url' => 'images/agents/vyse/ability2.webp',
                'ability3_url' => 'images/agents/vyse/ability3.webp',
                'ultimate_url' => 'images/agents/vyse/ultimate.webp',
            ],
            [
                'name' => 'Yoru',
                'role' => 'Duelist',
                'image_url' => 'images/agents/yoru.png',
                'bg_url' => 'images/agents/yoru/bg.jpg',
                'biography' => "A radiant from Tokyo, Japan, Kiritani Ryo (Japanese: 桐谷 諒) is a man dedicated to uncovering his past. Specifically interested in his ancestors and an ancient order of samurai, Kiritani's search has kept on bringing him to Kingdom's S22 container port. On his first visit, he broke into the facility and stole a mask from a set of samurai armor that allowed him to see into another dimension. He was later recruited by the VALORANT Protocol as its fifteenth agent, 'Yoru', and shortly after this his familiarity with S22 saw him returning there on assignment to prevent a spike detonation by hostiles from Omega Earth.",
                'ability1' => 'Fakeout',
                'ability2' => 'Blindside',
                'ability3' => 'Gatecrash',
                'ultimate' => 'Dimensional Drift',
                'ability1_desc' => 'Deploys a decoy of footsteps.',
                'ability2_desc' => 'Throws a flash grenade that bounces once.',
                'ability3_desc' => 'Teleports using a dimensional gate.',
                'ultimate_desc' => 'Becomes invisible and invulnerable in another dimension.',
                'ability1_url' => 'images/agents/yoru/ability1.webp',
                'ability2_url' => 'images/agents/yoru/ability2.webp',
                'ability3_url' => 'images/agents/yoru/ability3.webp',
                'ultimate_url' => 'images/agents/yoru/ultimate.webp',
            ]
        ];

        foreach ($agents as $agent) {
            Agent::create($agent);
        }
    }
}
